const translations = {
  en: {
    "nav_work": "Projects",
    "nav_exp": "Experience",
    "nav_stack": "Stack",
    "nav_about": "About",
    "nav_cv": "CV (PDF) ↓",
    "nav_contact": "Contact <span>↗</span>",
    "hero_eyebrow": "<span class=\"pulse\"></span> Full-Stack Developer &amp; AI Engineer",
    "hero_pitch": "Building production-grade web products, AI systems and intelligent automation.",
    "hero_title_1": "I build",
    "hero_title_2": "<span class=\"accent-text\">serious</span>",
    "hero_title_3": "software.",
    "hero_text": "Cherkaoui Abdessamad. Engineering robust web applications, AI-assisted platforms and scalable architectures — from system design to production deployment.",
    "hero_btn_work": "View selected work <span>↗</span>",
    "hero_btn_cv": "Download CV (PDF) ↓",
    "hero_btn_contact": "Let's talk",
    "hero_meta_1": "Rabat, Morocco",
    "hero_meta_2": "Open to opportunities",
    "floating_label_b": "AI / LLM",
    "floating_label_c": "SYSTEMS",
    "ticker_1": "FULL STACK",
    "ticker_2": "AI ENGINEERING",
    "ticker_3": "SECURE SYSTEMS",
    "work_eyebrow": "01 / Selected projects",
    "work_title": "Built for the<br><span class=\"accent-text\">real world.</span>",
    "p1_type": "ZERO-OPEX BYOK ARCHITECTURE · PEN-TESTED AI PLATFORM",
    "p1_headline": "Production job platform aggregating live Google Jobs and scoring candidate fit via Mistral AI with a hardened serverless BYOK proxy.",
    "p_visit": "Live Demo ↗",
    "pe_lbl_prob": "Problem:",
    "pe_lbl_sol": "Solution:",
    "pe_lbl_contrib": "Contribution:",
    "pe_lbl_impact": "Impact & Security:",
    "p1_problem": "Public AI apps face prohibitive LLM API costs (OpEx) and vulnerable client-side API key exposure.",
    "p1_solution": "Zero-OpEx 'BYOK Proxy' architecture: secure client key persistence piped through a hardened Vercel serverless proxy to Mistral AI & SerpApi.",
    "p1_contrib": "Engineered the serverless proxy, integrated Mistral AI & SerpApi, and hardened perimeter defenses (Rate Limiting, Helmet, 10kb payload limit).",
    "p1_impact": "Pen-tested against 500-request DDoS floods, 10MB payload bombs, and XSS fuzzing with 100% uptime and zero recurring OpEx.",
    "p1_ai_match": "MISTRAL AI MATCH",
    "p1_ai_chip": "BYOK SERVERLESS PROXY",
    "p2_type": "3D WEBGL & REACT-THREE-FIBER · LARAVEL 10 SANCTUM",
    "p2_headline": "High-end event platform with an interactive 3D procedural venue simulator, algorithmic seating chart, and automated booking funnel.",
    "p2_problem": "Manual venue planning is static and opaque, causing lengthy booking iteration and spatial miscalculations.",
    "p2_solution": "Procedural 3D venue engine (anti-occlusion Dollhouse camera, WebGL snapshots), automated seating algorithms, and Laravel 10 Sanctum API.",
    "p2_contrib": "Engineered the @react-three/fiber 3D engine, dynamic wall culling, Laravel 10 REST endpoints, and custom Vite vendor chunk splitting.",
    "p2_impact": "Lazy-loaded 3D chunks for instant initial page loads, 360° unobstructed spatial walkthroughs, and automated PDF quotation generation.",
    "p2_event": "3D SIMULATOR",
    "p3_type": "INSURTECH · FULL STACK MERN & NEXT.JS",
    "p3_headline": "Full-stack insurance agency platform featuring a dynamic quote simulator, automated email alerts, and a secure admin dashboard.",
    "p3_problem": "Traditional insurance intake relies on slow manual quotes and disjointed email threads, causing high drop-off rates.",
    "p3_solution": "MERN web application (Next.js, Node.js, MongoDB) with instant dynamic quote calculation, transactional email triggers, and protected staff back-office.",
    "p3_contrib": "Architected MongoDB schemas, engineered the real-time quote pricing engine, secure admin dashboard authentication, and automated email workflows.",
    "p3_impact": "Instant sub-second quote delivery, 100% digital onboarding, and centralized lead management with zero manual triage overhead.",
    "p4_type": "FULL-STACK MERN · FRAMER MOTION & DEDICATED ADMIN",
    "p4_headline": "Tactile, physics-animated MERN storefront with instant search, dynamic cart engine, and a dedicated React Admin Command Center.",
    "p4_problem": "Standard e-commerce templates feel rigid and disconnect customer storefronts from real-time admin inventory lifecycles.",
    "p4_solution": "Full-stack MERN architecture: Framer Motion spring physics storefront coupled to a dedicated React Admin portal (Multer uploads, live order tracking).",
    "p4_contrib": "Architected MongoDB schemas, engineered Context API cart/wishlist state, Multer image pipelines, and the complete Admin Command Center.",
    "p4_impact": "Sub-50ms instant search filtering, zero-lag useMemo re-renders, and seamless end-to-end order lifecycle tracking (Placed → Shipped → Delivered).",
    "p5_type": "OFFLINE-FIRST PWA · ENTERPRISE HR & ANALYTICS",
    "p5_headline": "Progressive Web Application for HR employee records management with Service Workers, instant SheetJS exports, and dynamic Chart.js analytics.",
    "p5_problem": "In-field HR teams frequently lose data connectivity when reviewing personnel records, risking data loss and delayed operations.",
    "p5_solution": "Offline-first PWA leveraging modern Service Workers, IndexedDB local caching, SheetJS client-side Excel/CSV generation, and Chart.js reporting.",
    "p5_contrib": "Engineered Service Worker offline sync, IndexedDB persistence layer, dynamic spreadsheet export engine, and modular HR dashboard views.",
    "p5_impact": "100% continuous offline uptime, instant zero-latency sheet exports, and automated personnel reporting with zero data loss.",
    "exp_eyebrow": "02 / Experience",
    "exp_title": "From freelance<br>to <span class=\"accent-text\">production.</span>",
    "exp1_title": "Full-Stack Web Developer &amp; Production Projects",
    "exp1_desc": "Architecture and engineering of full-stack web applications across academic, personal, and client projects, emphasizing clean code, modern standards, and peak performance.",
    "exp1_b1": "<strong>Engineered end-to-end modern CRUD applications</strong> using React on the frontend and Node.js / PHP on the backend, with robust form validation and dynamic state rendering.",
    "exp1_b2": "<strong>Modular frontend architecture &amp; REST API integration</strong>: built reusable UI component libraries and connected high-performance RESTful APIs for seamless client-server data flow.",
    "exp1_b3": "<strong>Relational database design &amp; schema management</strong>: modeled and optimized MySQL database architectures, relational queries, and data consistency safeguards.",
    "exp1_b4": "<strong>Responsive &amp; accessible web interfaces</strong> (HTML5, CSS3, modern JavaScript) backed by functional testing, rapid bug fixes, and runtime performance profiling.",
    "exp1_b5": "<strong>Git version control &amp; production deployment</strong>: managed disciplined Git/GitHub branching workflows and automated continuous deployments to Vercel and Netlify.",
    "exp2_title": "Web Developer — Public Sector Digital Archiving",
    "exp2_desc": "Designed and developed a digital archiving and records management web application for the Conseil de l'Arrondissement Agdal-Ryad in Rabat to digitize public administrative workflows.",
    "exp2_b1": "<strong>Needs Analysis &amp; Offline-First PWA Architecture</strong>: Analyzed public administration requirements, designed the responsive UI/UX, and developed an offline-first PWA with local data persistence.",
    "exp2_b2": "<strong>CRUD Operations, Auth &amp; Instant Search</strong>: Built complete CRUD records management, secure authentication, real-time search, and multi-criteria document filtering using React Context API.",
    "exp2_b3": "<strong>Analytics Dashboards &amp; Excel Import/Export</strong>: Integrated dynamic visual analytics charts using Chart.js and client-side Excel/CSV spreadsheet generation via SheetJS, deployed on Netlify.",
    "edu_eyebrow": "03 / Education",
    "edu_title": "Engineering mindset,<br><span class=\"accent-text\">continuous learning.</span>",
    "edu1_course": "Baccalaureate — Life and Earth Sciences",
    "edu1_status": "Baccalauréat",
    "edu2_course": "DTS — Digital Development, Full Stack Web Option",
    "edu2_status": "ISTA NTIC RABAT HAY RIAD · Bac +2",
    "edu3_course": "Bachelor's Degree — English Studies",
    "edu3_status": "Rabat · Ongoing",
    "stack_eyebrow": "04 / Skills",
    "stack_title": "A broad stack.<br><span class=\"accent-text\">Deep where it matters.</span>",
    "hub_text": "Technologies I use<br />to build modern<br />and scalable<br />solutions",
    "cat_front_desc": "Building interactive<br />and responsive<br />user interfaces",
    "cat_back_desc": "Server-side logic<br />and API<br />development",
    "cat_db_title": "Database &amp; Tools",
    "cat_db_desc": "Databases, tools<br />and utilities I rely on",
    "cat_core_title": "Core Competencies",
    "cat_core_desc": "Skills and values<br />that drive my work",
    "core_pm": "Project Management",
    "core_resp": "Responsive Web Design",
    "core_ai": "AI Integration",
    "core_team": "Team Spirit",
    "core_creative": "Creativity",
    "metrics_skills": "Production Apps",
    "metrics_skills_sub": "End-to-End Delivery",
    "metrics_proj": "Architecture Ownership",
    "metrics_proj_sub": "Design → Production",
    "metrics_roles": "Production Techs",
    "metrics_roles_sub": "Web, AI &amp; Databases",
    "metrics_edu": "Years Engineering",
    "metrics_edu_sub": "Professional Software",
    "about_eyebrow": "05 / About",
    "about_title": "I enjoy the part<br>where things get <span class=\"accent-text\">complex.</span>",
    "about_p1": "My focus is not limited to making interfaces look good. I like understanding the architecture underneath them: data flow, APIs, validation, security, performance, deployment and the edge cases that appear in real products.",
    "about_p2": "Alongside full-stack development, I build applied AI workflows — integrating semantic search, vector embeddings, and intelligent agents into products where automation delivers measurable business leverage.",
    "comp1_title": "Architectural Clarity",
    "comp1_desc": "Designing resilient, maintainable systems from ambiguous requirements with clean API contracts and data models.",
    "comp2_title": "Applied AI Integration",
    "comp2_desc": "Moving beyond basic wrappers: implementing vector search, semantic embeddings, and automated agent pipelines into real workflows.",
    "comp3_title": "Hardened for Production",
    "comp3_desc": "Taking prototypes across the finish line with strict error handling, resilient state, automated CI/CD, and fast load times.",
    "about_prin1": "Understand before building",
    "about_prin2": "Design systems, not patches",
    "about_prin3": "Ship measurable value",
    "contact_eyebrow": "Let's build something useful",
    "contact_title": "Have a difficult<br><span>problem?</span>",
    "contact_text": "Open to full-stack projects, AI products, technical collaborations and serious experiments.",
    "contact_btn": "Back to top ↑",
    "footer_role": "Full Stack · AI · Systems",
    "footer_cv": "Resume (PDF) ↗",
    "cv_modal_badge": "RESUME DOWNLOAD",
    "cv_modal_title": "Choose CV Language",
    "cv_modal_desc": "Select which version of the curriculum vitae you would like to download:",
    "cv_fr_title": "Version Française",
    "cv_fr_file": "CV professionnel Full-stack Abdessamad Cherkaoui",
    "cv_fr_meta": "PDF • 114 KB • Format Français",
    "cv_en_title": "English Version",
    "cv_en_file": "Professional Full-stack cv Abdessamad Cherkaoui",
    "cv_en_meta": "PDF • 62 KB • International Format",
    "cv_download_btn": "Download PDF ↓",
    "cv_toast_title": "Download Started",
    "cv_toast_fr": "Downloading French CV...",
    "cv_toast_en": "Downloading English CV..."
  },
  fr: {
    "nav_work": "Projets",
    "nav_exp": "Expérience",
    "nav_stack": "Technologies",
    "nav_about": "À propos",
    "nav_cv": "CV (PDF) ↓",
    "nav_contact": "Contact <span>↗</span>",
    "hero_eyebrow": "<span class=\"pulse\"></span> Développeur Full-Stack &amp; Ingénieur IA",
    "hero_pitch": "Conception de produits web de niveau production, systèmes d'IA et automatisation intelligente.",
    "hero_title_1": "Je conçois des",
    "hero_title_2": "<span class=\"accent-text\">logiciels</span>",
    "hero_title_3": "sérieux.",
    "hero_text": "Cherkaoui Abdessamad. Ingénierie d'applications web robustes, plateformes assistées par l'IA et architectures évolutives — de la conception au déploiement en production.",
    "hero_btn_work": "Voir mes projets <span>↗</span>",
    "hero_btn_cv": "Télécharger CV (PDF) ↓",
    "hero_btn_contact": "Discutons",
    "hero_meta_1": "Rabat, Maroc",
    "hero_meta_2": "À l'écoute d'opportunités",
    "floating_label_b": "IA / LLM",
    "floating_label_c": "SYSTÈMES",
    "ticker_1": "FULL STACK",
    "ticker_2": "INGÉNIERIE IA",
    "ticker_3": "SYSTÈMES SÉCURISÉS",
    "work_eyebrow": "01 / Projets sélectionnés",
    "work_title": "Conçus pour le<br><span class=\"accent-text\">monde réel.</span>",
    "p1_type": "ARCHITECTURE BYOK À COÛT ZÉRO · SYSTÈME IA AUDITÉ",
    "p1_headline": "Plateforme d'emploi agrégeant les offres Google Jobs et scorant les profils via Mistral AI avec un proxy serverless BYOK durci.",
    "p_visit": "Démo en ligne ↗",
    "pe_lbl_prob": "Problème :",
    "pe_lbl_sol": "Solution :",
    "pe_lbl_contrib": "Contribution :",
    "pe_lbl_impact": "Impact & Sécurité :",
    "p1_problem": "Les applications IA publiques souffrent de coûts d'API prohibitifs (OpEx) et de risques d'exposition des clés API côté client.",
    "p1_solution": "Architecture 'BYOK Proxy' à coût récurrent zéro : stockage sécurisé des clés en local, relayé via un proxy serverless Vercel vers Mistral AI et SerpApi.",
    "p1_contrib": "Conception du proxy serverless, intégration de Mistral AI & SerpApi, et renforcement périmétrique (Rate Limiting, Helmet, restriction 10kb).",
    "p1_impact": "Auditée et pen-testée avec succès contre des attaques DDoS de 500 requêtes, bombes JSON de 10 Mo et injections XSS sans plantage.",
    "p1_ai_match": "SCORE MISTRAL AI",
    "p1_ai_chip": "PROXY SERVERLESS BYOK",
    "p2_type": "WEBGL 3D & REACT-THREE-FIBER · LARAVEL 10 SANCTUM",
    "p2_headline": "Plateforme événementielle haut de gamme avec simulateur 3D procédural, planificateur de tables algorithmique et tunnel de devis automatisé.",
    "p2_problem": "L'estimation manuelle des salles est statique et imprécise, provoquant des frictions et des erreurs de disposition.",
    "p2_solution": "Moteur 3D procédural (vue Dollhouse anti-occlusion, capture WebGL), algorithme de plan de table et API Laravel 10 avec Sanctum.",
    "p2_contrib": "Développement du moteur @react-three/fiber, masquage dynamique des murs, API REST Laravel 10 et découpage de bundle Vite.",
    "p2_impact": "Lazy-loading du moteur 3D pour un chargement initial instantané, exploration 360° fluide et génération de devis PDF en un clic.",
    "p2_event": "SIMULATEUR 3D",
    "p3_type": "INSURTECH · APPLICATION FULL STACK MERN",
    "p3_headline": "Application full-stack MERN pour agence d'assurance avec simulateur de devis dynamique, notifications email et dashboard admin sécurisé.",
    "p3_problem": "La souscription traditionnelle par devis manuels et échanges papier ralentit le traitement et génère des abandons.",
    "p3_solution": "Plateforme MERN (Next.js, Node.js, MongoDB) avec simulateur de devis dynamique en temps réel, alertes email automatiques et back-office sécurisé.",
    "p3_contrib": "Modélisation de la base MongoDB, développement du moteur de calcul de devis, tableau de bord admin sécurisé et notifications email.",
    "p3_impact": "Délivrance de devis en moins d'une seconde, parcours client 100% digitalisé et gestion centralisée des dossiers agence.",
    "p4_type": "APPLICATION MERN COMPLÈTE · FRAMER MOTION & ADMIN",
    "p4_headline": "Boutique en ligne MERN tactile et animée par Framer Motion, avec recherche instantanée, panier dynamique et dashboard admin dédié.",
    "p4_problem": "Les templates e-commerce classiques sont rigides et déconnectent l'expérience d'achat de la gestion des stocks en temps réel.",
    "p4_solution": "Architecture MERN sur-mesure : storefront animé par physique de ressorts Framer Motion couplé à un portail admin dédié (uploads Multer, suivi commandes).",
    "p4_contrib": "Modélisation MongoDB, gestion de l'état panier/favoris via Context API, pipeline d'upload Multer et création du dashboard admin complet.",
    "p4_impact": "Filtrage catalogue en moins de 50ms, optimisations useMemo sans saccade et suivi complet du cycle de commande (Reçue → Expédiée → Livrée).",
    "p5_type": "PWA OFFLINE-FIRST · RH & ANALYTIQUE ENTREPRISE",
    "p5_headline": "Application web progressive pour départements RH et PME, avec persistance hors ligne Service Workers, exports SheetJS et graphiques Chart.js.",
    "p5_problem": "Les équipes RH sur le terrain perdent souvent leur connexion réseau, risquant la perte de données et bloquant les consultations.",
    "p5_solution": "PWA offline-first exploitant les Service Workers, le cache IndexedDB, la génération client Excel/CSV via SheetJS et des rapports Chart.js.",
    "p5_contrib": "Développement des Service Workers de synchronisation, persistance IndexedDB, moteur d'export de tableurs et interface RH modulaire.",
    "p5_impact": "Disponibilité continue à 100% hors ligne, exports tableurs instantanés sans latence serveur et zéro incident de perte de données.",
    "exp_eyebrow": "02 / Expérience",
    "exp_title": "Du freelance<br>à la <span class=\"accent-text\">production.</span>",
    "exp1_title": "Développeur Web Full-Stack &amp; Projets de Production",
    "exp1_desc": "Conception et développement d'applications web full stack dans le cadre de projets académiques, personnels et professionnels, avec une approche orientée bonnes pratiques et performance.",
    "exp1_b1": "<strong>Développement d'applications CRUD complètes &amp; modernes</strong> avec React en frontend et Node.js / PHP en backend, incluant validation des formulaires et affichage dynamique.",
    "exp1_b2": "<strong>Architectures frontend modulaires &amp; intégration d'API REST</strong> : mise en place de composants réutilisables et connexion d'APIs REST sécurisées.",
    "exp1_b3": "<strong>Conception &amp; gestion de bases de données relationnelles</strong> : modélisation de schémas MySQL optimisés, requêtes relationnelles et intégrité des données.",
    "exp1_b4": "<strong>Création d'interfaces responsives &amp; accessibles</strong> (HTML, CSS, JavaScript) avec tests fonctionnels, correction de bugs et optimisation des performances.",
    "exp1_b5": "<strong>Gestion du versioning &amp; déploiement continu</strong> : flux de travail Git &amp; GitHub, déploiement sur Vercel/Netlify et valorisation en production.",
    "exp2_title": "Développeur Web — Gestion &amp; Archivage Numérique",
    "exp2_desc": "Conception et développement d'une application web de gestion et d'archivage numérique pour le Conseil de l'Arrondissement Agdal-Ryad à Rabat, dans le cadre de la digitalisation des processus de gestion documentaire.",
    "exp2_b1": "<strong>Analyse des besoins &amp; Architecture PWA</strong> : Analyse des processus administratifs, conception UX/UI et développement d'une PWA moderne avec support hors ligne complet.",
    "exp2_b2": "<strong>Gestion CRUD, Authentification &amp; Recherche</strong> : Développement des opérations CRUD, authentification sécurisée, recherche en temps réel et filtrage avancé avec React Context API.",
    "exp2_b3": "<strong>Tableaux de bord, Statistiques &amp; Import/Export Excel</strong> : Intégration de graphiques statistiques dynamiques avec Chart.js et moteur d'import/export de tableurs avec SheetJS, déployé sur Netlify.",
    "edu_eyebrow": "03 / Formation",
    "edu_title": "Esprit d'ingénierie,<br><span class=\"accent-text\">apprentissage continu.</span>",
    "edu1_course": "Baccalauréat — Sciences de la vie et terre",
    "edu1_status": "Baccalauréat",
    "edu2_course": "DTS — Développement Digital, option Full Stack Web",
    "edu2_status": "ISTA NTIC RABAT HAY RIAD · Bac +2",
    "edu3_course": "Licence — Études anglaises",
    "edu3_status": "Rabat · En cours",
    "stack_eyebrow": "04 / Compétences",
    "stack_title": "Une stack large.<br><span class=\"accent-text\">Approfondie là où ça compte.</span>",
    "hub_text": "Technologies clés<br />pour concevoir des<br />solutions modernes<br />et scalables",
    "cat_front_desc": "Interfaces modernes,<br />interactives et<br />hautement responsives",
    "cat_back_desc": "Logique serveur,<br />architecture API<br />et performance",
    "cat_db_title": "Bases &amp; Outils",
    "cat_db_desc": "Bases de données,<br />outils et utilitaires<br />de développement",
    "cat_core_title": "Compétences clés",
    "cat_core_desc": "Méthodologie agile,<br />rigueur technique<br />et vision produit",
    "core_pm": "Gestion de projet",
    "core_resp": "Design Web Responsive",
    "core_ai": "Intégration IA",
    "core_team": "Esprit d'équipe",
    "core_creative": "Créativité",
    "metrics_skills": "Applications en prod",
    "metrics_skills_sub": "Livraison de bout en bout",
    "metrics_proj": "Responsabilité architecture",
    "metrics_proj_sub": "Conception → Déploiement",
    "metrics_roles": "Technologies en prod",
    "metrics_roles_sub": "Web, IA &amp; Bases de données",
    "metrics_edu": "Années d'ingénierie",
    "metrics_edu_sub": "Ingénierie logicielle",
    "about_eyebrow": "05 / À propos",
    "about_title": "J'apprécie le moment<br>où les choses deviennent <span class=\"accent-text\">complexes.</span>",
    "about_p1": "Mon objectif ne se limite pas à rendre les interfaces esthétiques. J'aime comprendre l'architecture sous-jacente : flux de données, API, validation, sécurité, performances, déploiement et les cas particuliers des produits réels.",
    "about_p2": "En plus du développement full-stack, j'élabore des workflows d'IA appliquée — intégrant recherche sémantique, embeddings vectoriels et agents intelligents lorsque l'automatisation apporte un réel levier.",
    "comp1_title": "Clarté architecturale",
    "comp1_desc": "Conception de systèmes résilients et maintenables à partir de besoins ambigus, avec contrats d'API et modèles de données clairs.",
    "comp2_title": "Intégration IA appliquée",
    "comp2_desc": "Au-delà des simples wrappers : recherche vectorielle, embeddings sémantiques et agents automatisés dans des flux réels.",
    "comp3_title": "Excellence en production",
    "comp3_desc": "Finalisation de prototypes vers la production : gestion d'erreurs robuste, état résilient, CI/CD et temps de chargement optimisés.",
    "about_prin1": "Comprendre avant de construire",
    "about_prin2": "Concevoir des systèmes, pas des correctifs",
    "about_prin3": "Livrer une valeur mesurable",
    "contact_eyebrow": "Construisons quelque chose d'utile",
    "contact_title": "Vous avez un problème<br><span>complexe ?</span>",
    "contact_text": "Ouvert aux projets full-stack, produits d'IA, collaborations techniques et expérimentations sérieuses.",
    "contact_btn": "Retour en haut ↑",
    "footer_role": "Full Stack · IA · Systèmes",
    "footer_cv": "CV (PDF) ↗",
    "cv_modal_badge": "TÉLÉCHARGEMENT DU CV",
    "cv_modal_title": "Choisissez la langue du CV",
    "cv_modal_desc": "Sélectionnez la version du curriculum vitae que vous souhaitez télécharger :",
    "cv_fr_title": "Version Française",
    "cv_fr_file": "CV professionnel Full-stack Abdessamad Cherkaoui",
    "cv_fr_meta": "PDF • 114 Ko • Format Français",
    "cv_en_title": "English Version",
    "cv_en_file": "Professional Full-stack cv Abdessamad Cherkaoui",
    "cv_en_meta": "PDF • 62 Ko • Format International",
    "cv_download_btn": "Télécharger PDF ↓",
    "cv_toast_title": "Téléchargement lancé",
    "cv_toast_fr": "Téléchargement du CV en français...",
    "cv_toast_en": "Téléchargement du CV en anglais..."
  }
};

const codeTranslations = {
  en: [
    'const profile = {',
    '  name: "Abdessamad Cherkaoui",',
    '  role: "Full-Stack Developer & AI Engineer",',
    '  location: "Morocco",',
    '',
    '  building: [',
    '    "Production Web Apps",',
    '    "AI Systems & Automation",',
    '    "Scalable Architectures"',
    '  ],',
    '',
    '  stack: "Next.js · React 19 · Node.js · Vector AI · SQL/NoSQL"',
    '};'
  ],
  fr: [
    'const profile = {',
    '  nom: "Abdessamad Cherkaoui",',
    '  role: "Développeur Full-Stack & Ingénieur IA",',
    '  localisation: "Maroc",',
    '',
    '  developpement: [',
    '    "Applications Web en Production",',
    '    "Systèmes IA & Automatisation",',
    '    "Architectures Scalables"',
    '  ],',
    '',
    '  stack: "Next.js · React 19 · Node.js · IA Vectorielle · SQL/NoSQL"',
    '};'
  ]
};
